### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by ric106** [galilean-traders/analysis#4]
Error occuring at the start of a new 5 min period. No errors reported from R server.
# Console writes:

error: Sending 500 ("Server Error") response: 
 Error: socket hang up
  at createHangUpError (http.js:1476:15)
  at Socket.socketOnEnd (http.js:1572:23)
  at Socket.g (events.js:180:16)
  at Socket.emit (events.js:117:20)
  at _stream_readable.js:943:16
  at process._tickDomainCallback (node.js:463:13)
 { [Error: socket hang up] code: 'ECONNRESET' }
Unhandled rejection StatusCodeError: 500 - [object Object]
  at new StatusCodeError (/Users/grandi/Desktop/Gtraders/analysis/node_modules/request-promise/lib/errors.js:26:15)
  at Request.RP$callback [as _callback](/Users/grandi/Desktop/Gtraders/analysis/node_modules/request-promise/lib/rp.js:58:34)
  at Request.self.callback (/Users/grandi/Desktop/Gtraders/analysis/node_modules/request-promise/node_modules/request/request.js:360:22)
  at Request.emit (events.js:98:17)
  at Request.<anonymous> (/Users/grandi/Desktop/Gtraders/analysis/node_modules/request-promise/node_modules/request/request.js:1202:14)
  at Request.emit (events.js:117:20)
  at IncomingMessage.<anonymous> (/Users/grandi/Desktop/Gtraders/analysis/node_modules/request-promise/node_modules/request/request.js:1150:12)
  at IncomingMessage.emit (events.js:117:20)
  at _stream_readable.js:943:16
  at process._tickDomainCallback (node.js:463:13)

error: Sending 500 ("Server Error") response: 
 RequestError: Error: connect EMFILE
  at new RequestError (/Users/grandi/Desktop/Gtraders/analysis/node_modules/request-promise/lib/errors.js:11:15)
  at Request.RP$callback [as _callback](/Users/grandi/Desktop/Gtraders/analysis/node_modules/request-promise/lib/rp.js:50:34)
  at self.callback (/Users/grandi/Desktop/Gtraders/analysis/node_modules/request-promise/node_modules/request/request.js:360:22)
  at Request.emit (events.js:95:17)
  at Request.onRequestError (/Users/grandi/Desktop/Gtraders/analysis/node_modules/request-promise/node_modules/request/request.js:1008:8)
  at ClientRequest.emit (events.js:95:17)
  at Socket.socketErrorListener (http.js:1551:9)
  at Socket.emit (events.js:95:17)
  at net.js:440:14
  at process._tickDomainCallback (node.js:463:13)
 { [RequestError: Error: connect EMFILE]
  name: 'RequestError',
  message: 'Error: connect EMFILE',
  cause: { [Error: connect EMFILE] code: 'EMFILE', errno: 'EMFILE', syscall: 'connect' },
  error: { [Error: connect EMFILE] code: 'EMFILE', errno: 'EMFILE', syscall: 'connect' },
  options: 
   { headers: { 'access-token': 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiIxfHVuZGVmaW5lZCIsInN1YiI6InN1YmplY3QiLCJhdWQiOiJnYWxpbGVhbi10cmFkZXJzIiwiZXhwIjoxNDI4Mzk4NDEyODI2LCJuYmYiOjE0Mjc3OTM2MTI4MjgsImlhdCI6MTQyNzc5MzYxMjgyOCwianRpIjoiMjI4ZTg1YzAtZDc4Ny0xMWU0LTg1M2MtZmY3MTZmNTc4MTc4In0.wYVO0GjvbRBlSnHKHVElyDlmq-IVVTqeuTjetPNWpGw' },
     method: 'POST',
     url: 'http://127.0.0.1:1337/api/instrument/ema10',
     json: 
      [ [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object] ],
     callback: undefined,
     uri: undefined,
     simple: true,
     resolveWithFullResponse: false },
  response: undefined }
error: Sending 500 ("Server Error") response: 
 Error: write EPIPE
  at errnoException (net.js:904:11)
  at Object.afterWrite (net.js:720:19)
 { [Error: write EPIPE] code: 'EPIPE', errno: 'EPIPE', syscall: 'write' }
error: Sending 500 ("Server Error") response: 
 Error: write EPIPE
  at errnoException (net.js:904:11)
  at Object.afterWrite (net.js:720:19)
 { [Error: write EPIPE] code: 'EPIPE', errno: 'EPIPE', syscall: 'write' }
error: Server Error:
# error: But no response could be sent because another error occurred:

**Comment by ric106** [comment]
Another error following after 5 min:

FATAL ERROR: CALL_AND_RETRY_2 Allocation failed - process out of memory
Abort trap: 6
